Table Guests {
    id int [pk]
    firstName varchar
    lastName varchar
    parkAreaId int [ref: > ParkAreas.id]
}

Table ParkAreas {
    id int [pk]
    title varchar
    guestId array [ref: > Guests.id]
    serviceId array [ref: <> Services.id] 
}

Table Services {
    id int [pk]
    attraction varchar
}